#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number

number=0
while [ $((number++)) -lt 100 ];
do
	if [ $((number % 15)) -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ $((number % 5)) -eq 0 ];
	then
		echo "Buzz"
	elif [ $((number % 3)) -eq 0 ];
	then
		echo "Fizz"
	else
		echo "$number"
	fi
done
