#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r usrname password usr_id grp_id uid_info home_dir cmd_shell
do
	echo "The user $usrname is part of the $grp_id gang, lives in $home_dir and rides $cmd_shell. $usr_id place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
