#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration,
#displays Best School and then Hi on a new line.

printVar=1
while [ $printVar -lt 11 ]
do
	if [ "$printVar" == "9" ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	printVar=$((printVar + 1))
done
