#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

printVar=1
while [ $printVar -lt 11 ]
do
        if [ "$printVar" == "4" ]
        then
                echo "bad luck"
	elif [ "$printVar" == "8" ]
	then
                echo "good luck"
        else
                echo "Best School"
        fi
        printVar=$((printVar + 1))
done
