#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
seconds=1
while [ $hours -le 12 ]
do
echo "Hours: $hours"
	while [ $seconds -lt 60 ]
	do
		echo "$seconds"
		seconds=$((seconds + 1))
	done
seconds=1
hours=$((hours + 1))
done
